[package]
name = "BeamedBlog"
version = "0.1.0"
authors = ["Beamed <beamed@umich.edu>"]

[dependencies]
diesel = { features = ["postgres"] }
diesel_codegen = { features = ["postgres"] }
dotenv = "0.9.0"
