[package]
name = "BeamedBlog"
version = "0.1.0"
authors = ["Beamed <beamed@umich.edu>"]

[dependencies]
diesel = { features = ["postgres"] }
diesel_codegen = { features = ["postgres"] }
rocket = "^0.3"
rocket_codegen = "^0.3"
rocket_contrib = "^0.3"
dotenv = "0.9.0"
bcrypt = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
csrf = "*"
data-encoding = "2.1.1"